#+TITLE: Project00 Key_Terms
#+LANGUAGE: en
#+OPTIONS: H:4 num:nil toc:nil \n:nil @:t ::t |:t ^:t *:t TeX:t LaTeX:t
#+OPTIONS: html-postamble:nil
#+STARTUP: showeverything entitiespretty
Websites used:
http://www.mathwords.com/

* Contrapositive
** identify
N/A
** Define
Contrapositives switch the hypothesis and conclusion of a logical
statement and then negate them both.
** Example/Explanation
p -> q is a logical conditional statement.

Let's suppose that p is "I drink water"
and q is "my thirst is quenched".
This equates to "If I drink water, my thirst is quenched."

The contrapositive of the conditional statement would be
~q -> ~p.

For our sentence this would be "If my thirst in not quenched,
I did not drink water".

The contrapositive of a true proposition is also true.

** Non-Trivial Test question
p is "I started reading book B" and q is "I finished reading book A".
What is the contrapositive of p -> q in sentence form?

Answer: "If I have not finished reading book A, I have not started reading book B".

* Converse
** identify
N/A
** Define
The converse of a proposition switches the hypothesis and conclusion.
** Example/Explanation
p -> q is a logical conditional statement.

Let's suppose that p is "I drink water"
and q is "my thirst is quenched".
This equates to "If I drink water, my thirst is quenched."

The converse of that conditional statement is 
q -> p.

The changes our statement to "If my thirst is quenched,
I must have drank water".

A proposition may be true, but the converse is not necessarily
true. As an example with the converse above, my thirst could be
quenched from drinking juice. It did not have to be water that I
was drinking.

** Non-Trivial Test question
p is "I started reading book B" and q is "I finished reading book A".
What is the converse of p -> q in sentence form?

Answer: "If I finished reading book A, I have started reading book B".

* inverse
** identify
N/A
** Define
The inverse of a proposition negates the hypothesis and the conclusion.
** Example/Explanation
p -> q is a logical conditional statement.

Let's suppose that p is "I drink water"
and q is "my thirst is quenched".
This equates to "If I drink water, my thirst is quenched."

~p -> ~q is the inverse of our conditional statement.

In sentence form, this is "If I did not drink water, my thrist is not quenched".

A proposition may be true, but the inverse might be false.

** Non-Trivial Test question
p is "I started reading book B" and q is "I finished reading book A".
What is the inverse of p -> q in sentence form?

Answer: "If I haven't finished reading book A, I haven't started reading book B".

* R: real numbers
** identify
R is the set of all real numbers.

** Define
R is the set of all real numbers, and real numbers are all of the numbers that 
are on a number line.

** Example/Explanation
The set of all real numbers includes all positive, negative, whole, and floating point numbers.

** Non-Trivial Test question
Which of the following is NOT a real number.
a. 3.14159

b. 867.5309

c. sqrt(-1)

d. 42

* Z: integers
** identify
Z is the set of all integers.

** Define
Z is the set of all integers, and integers are all the whole numbers.

** Example/Explanation
The set of all integers is all of the negative and positive whole numbers.
This means that floating point and fraction numbers are not included in this
set.

** Non-Trivial Test question
x is an even number. Which of the following do we know is true?

a. x is a negative number

b. x is a positive number

c. x is not in Z

d. x is in is Z

* Q: rational numbers
** identify
Q is the set of all rational numbers.

** Define
Q is the set of all rational number, and rational numbers are numbers 
are a subset of R where the real numbers can be represented by a ratio
of integers where the denominator is an non-zero integer.

** Example/Explanation
Any number that can be represented either as a whole number or as a 
ratio of integers is in the set Q. This can include numbers that have 
a repeating decimal such as .333333... (which can be represented as 1 / 3).
Numbers (like e) that cannot be represented as a fraction of integers are 
not included in this set.

** Non-Trivial Test question
True or false: Pi is a rational number.

Answer: false

* predicate
** identify
N/A

** Define
A predicate is a function whose codomain is the set [true false].
The domain can be any conceivable set, however.

** Example/Explanation
A predicate basically comes down to being a function that returns a boolean,
and it can have any number of inputs and any type of input.

An example of a predicate could be a function that takes a year and 
return true if the year is a leap year or false if it is not a leap
year.

Predicates are similar to propositions.

** Non-Trivial Test question
Which of the following functions would be a predicate?

a. isEmpty()

b. getNumItems()

c. a and b

d. None of the above

* Domain
** identify
N/A

** Define
The domain is the set of all possible inputs for a function.

** Example/Explanation
Domains vary from function to function.

For a function that could only take positive integers for arguments,
the domain would be Z+ ( or all positive integers ).

If a function could take any number, the domain would be R ( or all real numbers ).

** Non-Trivial Test question
What is the domain of this C++ function?

// prototype
bool myFunc(long num);

a. R

b. Z

c. Q

d. None of the above

* CoDomain
** identify
N/A

** Define
The codomain is the set of all possible outputs of a function.

** Example/Explanation
Whatever the return type of a function is determines the codomain.

** Non-Trivial Test question
What is the codomain of this C++ function?

// prototype
bool myFunc(long num);

a. R

b. Z

c. Q

d. [true false]

* quantifier
** identify
https://en.wikipedia.org/wiki/Quantifier_(logic)

** Define
"In logic, quantification specifies the quantity of specimens in the domain of discourse that satisfy an open formula...
A language element which generates a quantification (such as "every") is called a quantifier."
   - Taken from the wikipedia article (see link in identify)
     
** Example/Explanation
Two of the most common quantifiers are "for all" and "there exists".

These both can give a quantity for a logical statement:
"For all students in this room, there exists at least one chair."

** Non-Trivial Test question
What are the quantifiers of the following sentence?
"For all students in this room, there exists at least one chair."

a. For all

b. there exists

c. students

d. a and b

* antecedent
** identify
N/A

** Define
This is the first half of a logical proposition.

** Example/Explanation
In the conditional statement p -> q, p is the antecedent.

For the phrase "I drink water, then I am not thirsty",
the antecedent is "I drink water".

** Non-Trivial Test question
Circle the antecedent:
"I drink water, then I am not thirsty." 
--------------------------------------------------------------------------------

* consequent
** identify
N/A

** Define
This is the second  half of a logical statement.

** Example/Explanation
In the conditional statement p -> q, q is the consequent. 

For the phrase "I drink water, then I am not thirsty",
the consequent is "I am not thirsty".

** Non-Trivial Test question
Circle the consequent:
"I drink water, then I am not thirsty." 
--------------------------------------------------------------------------------

* Set
** identify
N/A
** Define
A group of values/items which represent all the possible inputs,
possible outputs or actual outputs of a function.
** Example/Explanation
Sets give you a list of values which all meet the same requirements.
It can either be a finite set, such as a list of numbers: 
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9] 
or it can be an infinite set, such as a set of numbers which are all multiples
of 3.
** Non-Trivial Test question
Which number does not belong to the following set?
a. 16
b. 41
c. 8
d. 32
----------------------------------------------------------------------------------

* Fallacy
** identify
N/A
** Define
A mistaken belief or failure in reasoning that renders an argument invalid.
** Example/Explanation
Fallacy's are faulty logic, which can occur with boolean tables that have
incorrect inputs. For example: "All Jedi's have lightsabers" and "Taylor has
a lightsaber" so "Taylor must be a Jedi" is a fallacy, since owning a lightsaber
does not necissarily make one a Jedi. Taylor is certainly not one!
** Non-Trivial Test question
Given the statment "If it snows, then it is cold outside", which of the following
is a fallacy?
a. It snowed, so it must be cold outside
b. It is cold, so it must have snowed
c. It did not snow, therefore it is not cold outside
d. both b & c.
-------------------------------------------------------------------------------------

* biconditional
** identify
<-->
** Define
Statements whuch are true whenever both parts have the same truth value
** Example/Explanation
"p if and only if q" is an example of a biconditional statement and is represented 
by p <--> q, where p and q must either both be true or both be false to output a "1" or
"true" value.
** Non-Trivial Test question
given: p: A student at BYU-I is full-time.
       q: A student has atleast 12 credits.
How would you write the biconditional statement p <--> q given these two statements?
--------------------------------------------------------------------------------------

* sufficient condition
** identify
N/A
** Define
A condition that must be satisfied for a statement to be true and without which the
statement cannot be true.
** Example/Explanation
** Non-Trivial Test question
For example: A sufficient condition for getting an A in the Discreet Math class would be
to get an A on all the assignments. :) If you can do that, it is "sufficient" to get
an A in the class.
** Non-Trivial Test question
Mark the following as true or false:
T  F  Being a girl is sufficient conditon for being a wife.
T  F  Being a wife is sufficient condition for being a girl.
T  F  Being dead is sufficient condition for being murdered.
T  F  Being murdered is sufficient condition for being dead.
-------------------------------------------------------------------------------------------

* necessary condition
** identify
N/A
** Define
A condition that must be satisfied for a statement to be true, but that is not in
and of itself necessarily true.
** Example/Explanation
For example: A necessary condition to get an A in Discreet math is to turn in your
projects. If you don't turn them in, you won't get an A... but turning them in does 
not autimatically insure the grade either.
** Non-Trivial Test question
Mark the following as true or false:
T  F  A necessary condition to be judged in court is to be accused of something.
T  F  Being alive is a necessary condition for having a right to live.
T  F  If I am self-made and rich, then it is a necessary condition that I worked hard.
------------------------------------------------------------------------------------------

* ~p
** identify
Not p or negation
** Define
The tilde (~) is used to negate the value of p. Meaning it will become 0, instead of 1
or vise versa.
** Example/Explanation
If p's value is 1, then ~p is worth 0. Because the "~" symbol negates the value of p.
Another example would be if p = raining outside, then ~p = not raining outside.
** Non-Trivial Test question
How would you write "if q and not-p"?
----------------------------------------------------------------------------------------

* p ^ q
** identify
p and q.
** Define
Used to mean that a statement is true only if both p and q are true.
** Example/Explanation
For example: I want my phone to unlock only if I press the power button AND enter the
password. So, using the equation p ^ q where p represents the power being on and q
is the correct password being entered could be used to represent whether or not my
phone will unlock.
** Non-Trivial Test question
Write the truth table for the equation p ^ q.
---------------------------------------------------------------------------------------

* p V q
** identify
p or q.
** Define
Used to mean that a statement is true if p or q or both are true.
** Example/Explanation
For example: I will only be friends with someone who owns a cat or a dog. I can use the
equation p V q where p represents owning a cat and q represents owning a dog to show 
whether or not I will be friends with a person.
** Non-Trivial Test question
Fill in the following blanks on the truth table
p | q | p V q
--------------
0 | 0 |  
0 | 1 |  
1 | 0 |  
1 | 1 |
-------------------------------------------------------------------------------------

* p XOR q
** identify
** Define
** Example/Explanation
** Non-Trivial Test question

* p == q
** identify
** Define
** Example/Explanation
** Non-Trivial Test question

* p -> q
** identify
** Define
** Example/Explanation
** Non-Trivial Test question

* p <--> q
** identify
** Define
** Example/Explanation
** Non-Trivial Test question

* Three dots in a triangle
** identify
** Define
** Example/Explanation
** Non-Trivial Test question

* upside down A
** identify
** Define
** Example/Explanation
** Non-Trivial Test question

* Backwards E
** identify
** Define
** Example/Explanation
** Non-Trivial Test question

* union
** identify
** Define
** Example/Explanation
** Non-Trivial Test question

* negation laws
** identify
** Define
** Example/Explanation
** Non-Trivial Test question

* double negative law*
** identify
** Define
** Example/Explanation
** Non-Trivial Test question

* idempotent laws
** identify
** Define
** Example/Explanation
** Non-Trivial Test question

* universal bound laws
** identify
** Define
** Example/Explanation
** Non-Trivial Test question

* De morgan's laws
** identify
** Define
** Example/Explanation
** Non-Trivial Test question

* absorption law
** identify
** Define
** Example/Explanation
** Non-Trivial Test question

* negations of t and c
** identify
** Define
** Example/Explanation
** Non-Trivial Test question

* vacuously true
** identify
** Define
** Example/Explanation
** Non-Trivial Test question

* Modus Ponens
** identify
** Define
** Example/Explanation
** Non-Trivial Test question

* Modus Tollens
** identify
** Define
** Example/Explanation
** Non-Trivial Test question

* Elimination: valid argument form
** identify
** Define
** Example/Explanation
** Non-Trivial Test question

* Transitivity: Valid Argument form
** identify
** Define
** Example/Explanation
** Non-Trivial Test question
