#+TITLE: Project00 Key_Terms
#+LANGUAGE: en
#+OPTIONS: H:4 num:nil toc:nil \n:nil @:t ::t |:t ^:t *:t TeX:t LaTeX:t
#+OPTIONS: html-postamble:nil
#+STARTUP: showeverything entitiespretty
Websites used:
http://www.mathwords.com/

* Contrapositive
** identify
N/A
** Define
Contrapositives switch the hypothesis and conclusion of a logical
statement and then negate them both.
** Example/Explanation
p -> q is a logical conditional statement.

Let's suppose that p is "I drink water"
and q is "my thirst is quenched".
This equates to "If I drink water, my thirst is quenched."

The contrapositive of the conditional statement would be
~q -> ~p.

For our sentence this would be "If my thirst in not quenched,
I did not drink water".

The contrapositive of a true proposition is also true.

** Non-Trivial Test question
p is "I started reading book B" and q is "I finished reading book A".
What is the contrapositive of p -> q in sentence form?

Answer: "If I have not finished reading book A, I have not started reading book B".

* Converse
** identify
N/A
** Define
The converse of a proposition switches the hypothesis and conclusion.
** Example/Explanation
p -> q is a logical conditional statement.

Let's suppose that p is "I drink water"
and q is "my thirst is quenched".
This equates to "If I drink water, my thirst is quenched."

The converse of that conditional statement is 
q -> p.

The changes our statement to "If my thirst is quenched,
I must have drank water".

A proposition may be true, but the converse is not necessarily
true. As an example with the converse above, my thirst could be
quenched from drinking juice. It did not have to be water that I
was drinking.

** Non-Trivial Test question
p is "I started reading book B" and q is "I finished reading book A".
What is the converse of p -> q in sentence form?

Answer: "If I finished reading book A, I have started reading book B".

* inverse
** identify
N/A
** Define
The inverse of a proposition negates the hypothesis and the conclusion.
** Example/Explanation
p -> q is a logical conditional statement.

Let's suppose that p is "I drink water"
and q is "my thirst is quenched".
This equates to "If I drink water, my thirst is quenched."

~p -> ~q is the inverse of our conditional statement.

In sentence form, this is "If I did not drink water, my thrist is not quenched".

A proposition may be true, but the inverse might be false.

** Non-Trivial Test question
p is "I started reading book B" and q is "I finished reading book A".
What is the inverse of p -> q in sentence form?

Answer: "If I haven't finished reading book A, I haven't started reading book B".

* R: real numbers
** identify
R is the set of all real numbers.

** Define
R is the set of all real numbers, and real numbers are all of the numbers that 
are on a number line.

** Example/Explanation
The set of all real numbers includes all positive, negative, whole, and floating point numbers.

** Non-Trivial Test question
Which of the following is NOT a real number.
a. 3.14159

b. 867.5309

c. sqrt(-1)

d. 42

* Z: integers
** identify
Z is the set of all integers.

** Define
Z is the set of all integers, and integers are all the whole numbers.

** Example/Explanation
The set of all integers is all of the negative and positive whole numbers.
This means that floating point and fraction numbers are not included in this
set.

** Non-Trivial Test question
x is an even number. Which of the following do we know is true?

a. x is a negative number

b. x is a positive number

c. x is not in Z

d. x is in is Z

* Q: rational numbers
** identify
Q is the set of all rational numbers.

** Define
Q is the set of all rational number, and rational numbers are numbers 
are a subset of R where the real numbers can be represented by a ratio
of integers where the denominator is an non-zero integer.

** Example/Explanation
Any number that can be represented either as a whole number or as a 
ratio of integers is in the set Q. This can include numbers that have 
a repeating decimal such as .333333... (which can be represented as 1 / 3).
Numbers (like e) that cannot be represented as a fraction of integers are 
not included in this set.

** Non-Trivial Test question
True or false: Pi is a rational number.

Answer: false

* predicate
** identify
N/A

** Define
A predicate is a function whose codomain is the set [true false].
The domain can be any conceivable set, however.

** Example/Explanation
A predicate basically comes down to being a function that returns a boolean,
and it can have any number of inputs and any type of input.

An example of a predicate could be a function that takes a year and 
return true if the year is a leap year or false if it is not a leap
year.

Predicates are similar to propositions.

** Non-Trivial Test question
Which of the following functions would be a predicate?

a. isEmpty()

b. getNumItems()

c. a and b

d. None of the above

* Domain
** identify
N/A

** Define
The domain is the set of all possible inputs for a function.

** Example/Explanation
Domains vary from function to function.

For a function that could only take positive integers for arguments,
the domain would be Z+ ( or all positive integers ).

If a function could take any number, the domain would be R ( or all real numbers ).

** Non-Trivial Test question
What is the domain of this C++ function?

// prototype
bool myFunc(long num);

a. R

b. Z

c. Q

d. None of the above

* CoDomain
** identify
N/A

** Define
The codomain is the set of all possible outputs of a function.

** Example/Explanation
Whatever the return type of a function is determines the codomain.

** Non-Trivial Test question
What is the codomain of this C++ function?

// prototype
bool myFunc(long num);

a. R

b. Z

c. Q

d. [true false]

* quantifier
** identify
https://en.wikipedia.org/wiki/Quantifier_(logic)

** Define
"In logic, quantification specifies the quantity of specimens in the domain of discourse that satisfy an open formula...
A language element which generates a quantification (such as "every") is called a quantifier."
   - Taken from the wikipedia article (see link in identify)
     
** Example/Explanation
Two of the most common quantifiers are "for all" and "there exists".

These both can give a quantity for a logical statement:
"For all students in this room, there exists at least one chair."

** Non-Trivial Test question
What are the quantifiers of the following sentence?
"For all students in this room, there exists at least one chair."

a. For all

b. there exists

c. students

d. a and b

* antecedent
** identify
N/A

** Define
This is the first half of a logical proposition.

** Example/Explanation
In the conditional statement p -> q, p is the antecedent.

For the phrase "I drink water, then I am not thirsty",
the antecedent is "I drink water".

** Non-Trivial Test question
Circle the antecedent:
"I drink water, then I am not thirsty." 
--------------------------------------------------------------------------------

* consequent
** identify
N/A

** Define
This is the second  half of a logical statement.

** Example/Explanation
In the conditional statement p -> q, q is the consequent. 

For the phrase "I drink water, then I am not thirsty",
the consequent is "I am not thirsty".

** Non-Trivial Test question
Circle the consequent:
"I drink water, then I am not thirsty." 
--------------------------------------------------------------------------------

* Set
** identify
N/A
** Define
A group of values/items which represent all the possible inputs,
possible outputs or actual outputs of a function.
** Example/Explanation
Sets give you a list of values which all meet the same requirements.
It can either be a finite set, such as a list of numbers: 
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9] 
or it can be an infinite set, such as a set of numbers which are all multiples
of 3.
** Non-Trivial Test question
Which number does not belong to the following set?
a. 16
b. 41
c. 8
d. 32
----------------------------------------------------------------------------------

* Fallacy
** identify
N/A
** Define
A mistaken belief or failure in reasoning that renders an argument invalid.
** Example/Explanation
Fallacy's are faulty logic, which can occur with boolean tables that have
incorrect inputs. For example: "All Jedi's have lightsabers" and "Taylor has
a lightsaber" so "Taylor must be a Jedi" is a fallacy, since owning a lightsaber
does not necissarily make one a Jedi. Taylor is certainly not one!
** Non-Trivial Test question
Given the statment "If it snows, then it is cold outside", which of the following
is a fallacy?
a. It snowed, so it must be cold outside
b. It is cold, so it must have snowed
c. It did not snow, therefore it is not cold outside
d. both b & c.
-------------------------------------------------------------------------------------

* biconditional
** identify
<-->
** Define
Statements whuch are true whenever both parts have the same truth value
** Example/Explanation
"p if and only if q" is an example of a biconditional statement and is represented 
by p <--> q, where p and q must either both be true or both be false to output a "1" or
"true" value.
** Non-Trivial Test question
given: p: A student at BYU-I is full-time.
       q: A student has atleast 12 credits.
How would you write the biconditional statement p <--> q given these two statements?
--------------------------------------------------------------------------------------

* sufficient condition
** identify
N/A
** Define
A condition that must be satisfied for a statement to be true and without which the
statement cannot be true.
** Example/Explanation
** Non-Trivial Test question
For example: A sufficient condition for getting an A in the Discreet Math class would be
to get an A on all the assignments. :) If you can do that, it is "sufficient" to get
an A in the class.
** Non-Trivial Test question
Mark the following as true or false:
T  F  Being a girl is sufficient conditon for being a wife.
T  F  Being a wife is sufficient condition for being a girl.
T  F  Being dead is sufficient condition for being murdered.
T  F  Being murdered is sufficient condition for being dead.
-------------------------------------------------------------------------------------------

* necessary condition
** identify
N/A
** Define
A condition that must be satisfied for a statement to be true, but that is not in
and of itself necessarily true.
** Example/Explanation
For example: A necessary condition to get an A in Discreet math is to turn in your
projects. If you don't turn them in, you won't get an A... but turning them in does 
not autimatically insure the grade either.
** Non-Trivial Test question
Mark the following as true or false:
T  F  A necessary condition to be judged in court is to be accused of something.
T  F  Being alive is a necessary condition for having a right to live.
T  F  If I am self-made and rich, then it is a necessary condition that I worked hard.
------------------------------------------------------------------------------------------

* ~p
** identify
Not p or negation
** Define
The tilde (~) is used to negate the value of p. Meaning it will become 0, instead of 1
or vise versa.
** Truth Table:
p  ~p
0  1
1  0
** Example/Explanation
If p's value is 1, then ~p is worth 0. Because the "~" symbol negates the value of p.
Another example would be if p = raining outside, then ~p = not raining outside.
** Non-Trivial Test question
How would you write "if q and not-p"?
----------------------------------------------------------------------------------------

* p ^ q
** identify
p and q.
** Define
Used to mean that a statement is true only if both p and q are true.
** Truth Table:
p  q  p ^ q
0  0    0
0  1    0
1  0    0
1  1    1
** Example/Explanation
For example: I want my phone to unlock only if I press the power button AND enter the
password. So, using the equation p ^ q where p represents the power being on and q
is the correct password being entered could be used to represent whether or not my
phone will unlock.
** Non-Trivial Test question
Write the truth table for the equation p ^ q.
---------------------------------------------------------------------------------------

* p V q
** identify
p or q.
** Define
Used to mean that a statement is true if p or q or both are true.
** Truth Table
p  q  p V q
0  0    0
0  1    1
1  0    1
1  1    1
** Example/Explanation
For example: I will only be friends with someone who owns a cat or a dog. I can use the
equation p V q where p represents owning a cat and q represents owning a dog to show 
whether or not I will be friends with a person.
** Non-Trivial Test question
create a truth table for the equation p V q.
-------------------------------------------------------------------------------------

* p XOR q
** identify'
exclusively p or q, but not both.
** Define
Used to mean that a statement is true only if p OR q is true, but not if both of them
are true.
** Truth Table
p  q  p XOR q
0  0     0
0  1     1
1  0     1
1  1     0
** Example/Explanation
For example: I only want one pet, either a cat or a dog but not both. I can use the
equation p XOR q to reptrsent this, where p represents owning a cat and q represents
owning a dog to show wether or not I own one pet.
** Non-Trivial Test question
create a truth table for the equation p XOR q.
-------------------------------------------------------------------------------------

* p == q
** identify
p and q are equal.
** Define
Used to mean that p and q are equal to each other. If they are not equal, then
the statement is false.
** truth table
p  q  p == q
0  0    1
0  1    0
1  0    0
1  1    1
** Example/Explanation
For example: If we want to know if we both own pets, p could represent me owning a pet
and q could represent you owning a pet. So if p and q are both 0, it is true that we both
don't own pets and if p and q are 1, it is true that we both own pets.
** Non-Trivial Test question
write a truth table for the equation p == q.
---------------------------------------------------------------------------------------

* p -> q
** identify
q is a result of p.
** Define
This means that q will result in p.
** truth table
p  q  p -> q
0  0    1
0  1    1
1  0    0
1  1    1
** Example/Explanation
Given that p represents drinking water and q represents feeling quenched, using the above
truth table we can see that it fits for this statement. I can either not drink water and
not be quenched, not drink water since I am already quenched, or drink water and be quenched.
But I cannot drink water and not be quenched.
** Non-Trivial Test question
create a truth table for the equation p -> q.
----------------------------------------------------------------------------------------

* p <--> q
** identify
Biconditional statement
** truth table
p  q  p <--> q
0  0     1
0  1     0
1  0     0
1  1     1
** Define
The output is only true if both p and q are false or both p and q are true.
** Example/Explanation
For example, I could say that p represents battery full and q represents screen on. The
output is a notification. So, using the equation p <--> q, a notification will only be
output if either the battery is full and the screen is on, or the battery is not full and
the screen is off.
** Non-Trivial Test question
create a truth table for the equation p <--> q.
----------------------------------------------------------------------------------------

* Three dots in a triangle
** identify
Therefore
** Define
It is a shorthand way of saying therefore. Or because of this, THEREFORE that.
** Example/Explanation
For example, the statements all God's are immortal, and Zeus is a God. We could use the
Three dots in a triangle to say "therefore, Zeus is immortal". Connecting the two statements
together.
** Non-Trivial Test question
Which of the following is a correct "therefore" statement, given that God's are immortal and
Zeus is a God.
a. Therefore, Zeus is immortal
b. Therefore, God is Zeus
c. a & b
d. neither a nor b
-----------------------------------------------------------------------------------------

* upside down A
** identify
Universal Quantification
** Define
Meaning "for all, for any, or for each" that P(x) is true for each x.
** Example/Explanation
One example would be that for every sneeze, a person blinks. Because in our universe, a
person's eyes will always naturally close whenever they blink. P(x) holds for each case of
x.
** Non-Trivial Test question
Which of the following statements can be expressed using universal quantification?
a. All functioning cars have wheels
b. All cats are pets
c. Everyone likes pineapple
d. Everyone knows Taylor Swift
-------------------------------------------------------------------------------------------

* Backwards E
** identify
existensial quantification
** Define
meaning "there exists" or that for any function, there exists atleast one x such that P(x)
is true.
** Example/Explanation
For example, saying "someone loves you" is existential quantification because it means that
there is atleast someone in the whole universe who loves you. As long as there IS someone,
this is a true statement.
** Non-Trivial Test question
Which of the following is an Existensial quantification?
a. There exists a dog who can speak english.
b. There are people living on the moon.
c. There exists a person who can pass discreet math class.
d. There exists a living T-Rex on the earth.
------------------------------------------------------------------------------------------------

* union
** identify
N/A
** Define
The union of two sets is everything from both sets.
** Example/Explanation
For example, if I have the sets {1, 2, 3} and {3, 4, 5}, then the union of the two sets would be
{1, 2, 3, 4, 5}.
** Non-Trivial Test question
Suppose that we have two sets:
set 1: {1, 3, 5, 6}
set 2: {1, 2, 4, 6, 7}
what would be the proer way to write a union formed between the two sets?
-------------------------------------------------------------------------------------------------

* negation laws
** identify
~
** Define
The law of negation is to make something ineffective or invalid. As the name implies, it
is to "negate" something. It is also important to note, that when negating an AND statement,
the AND will become an OR. And when negating an OR statement, the OR will become an AND.
** Example/Explanation
For example, if I have the statement, "I am both rich AND happy" where p = rich and q = happy
(p ^ q) then the negative statement would be "I am not rich OR I am not happy" (~p V ~q).
** Non-Trivial Test question
Negate the following statements:
1. I am eating and I am happy.
2. If I am at disneyland, then I am happy.
3. I have a dog or I have a cat.
------------------------------------------------------------------------------------------------

* double negative law*
** identify
~~
** Define
Double negation can sometimes be called the law of cancelation, because it cancels the negatives
out and makes the statement positive. They can be used in the perfomance of "indirect proofs".
** Example/Explanation
"If it is untrue that A is untrue, then A is true". This is an example of the double negative law.
One more way to write it would be ~(~p), or in other words p.
** Non-Trivial Test question
What is the equivalent of the following function: ~(~p)
a. ~p
b. not p
c. 0
d. p
------------------------------------------------------------------------------------------------------

* idempotent laws
** identify
** Define
   In Boolean algebra, Idempotent Law states that combining a quantity with itself either by logical 
   addition or logical multiplication will result in a logical sum or product that is the equivalent 
   of the quantity.
** Example/Explanation
   A + A = A; A x A = A 
** Non-Trivial Test question
   Give an example of an Idempotent law using real numbers.
* universal bound laws
** identify
** Define
   When both sides of a logical statement are equivalent to each other.
** Example/Explanation
   p∧c≡c
** Non-Trivial Test question
   

* De morgan's laws
** identify
** Define
   The complement of the union of two sets is equal to the intersection of their complements 
   and the complement of the intersection of two sets is equal to the union of their complements.
** Example/Explanation
   (A ∩ B)' = A' U B'

   Let M = (A ∩ B)' and N = A' U B'

   Let x be an arbitrary element of M then x ∈ M ⇒ x ∈ (A ∩ B)'

   ⇒ x ∉ (A ∩ B)

   ⇒ x ∉ A or x ∉ B

   ⇒ x ∈ A' or x ∈ B'

   ⇒ x ∈ A' U B'

   ⇒ x ∈ N

   Therefore, M ⊂ N

** Non-Trivial Test question
   If two sets A = {1,2,3,4,5,6} and B = {2,3,4,8} then prove that (A ∩ B)' = A' ∪ B'

* absorption law
** identify
** Define
   a theorem in logic: to affirm that either some proposition is true or else that 
   that proposition and some other proposition are both true is equivalent to affirming 
   the first proposition.
** Example/Explanation
   p ∨ (p ∧ q) ≡ p, p ∧ (p ∨ q) ≡ p
** Non-Trivial Test question
   Which one shows an example of an absorption law?

   A. p∧q≡q∧p,p∨q≡q∨p

   B.(p∧q)∧r ≡p∧(q∧r) 
     (p∨q)∨r ≡p∨(q∨r)
   
   C. p ∨ (q ∧ r) ≡ (p ∨ q) ∧ (p ∨ r)
      p ∧ (q ∨ r) ≡ (p ∧ q) ∨ (p ∧ r)

   D. p ∨ (p ∧ q) ≡ p, p ∧ (p ∨ q) ≡ p
   

* negations of t and c
** identify
   The negations of tautology and a contradiction
** Define
   Negating a tautology would always make it false
   and negating a contradiction would always make it true.
** Example/Explanation
   p ∨ ¬ p
   is a tautology.

   ~(p v ¬p)
   is not a tautology

   p ∧ ¬ p
   is a contradiction.

   ~(p ∧ ¬ p)
   is not a contradiction

** Non-Trivial Test question
   Is a negated tautology a contradiction?

* vacuously true
** identify
** Define
** Example/Explanation
   The statement "all cell phones in the room are turned off" will be true whenever there are no cell phones in the room. 
   In this case, the statement "all cell phones in the room are turned on" would also be vacuously true, as would the conjunction of the two: 
   "all cell phones in the room are turned on and turned off".
** Non-Trivial Test question

* Modus Ponens
** identify
** Define
** Example/Explanation
** Non-Trivial Test question

* Modus Tollens
** identify
** Define
** Example/Explanation
** Non-Trivial Test question

* Elimination: valid argument form
** identify
** Define
** Example/Explanation
** Non-Trivial Test question

* Transitivity: Valid Argument form
** identify
** Define
** Example/Explanation
** Non-Trivial Test question
